### ISSUE TITLE
Create web-interface

### ISSUE THREAD

**Issue by sadbuttrue1** [therods/YetAnotherToDoList#10]
Поверх существующего контроллера нужно сделать web-интерфейс например на jsp. Он должен уметь:

- [x] Показывать все задачи

- [x] Давать возможность добавить новую

- [x] Удалять существующие

- [x] Редактировать существующие

http://www.javatpoint.com/crud-in-jsp вроде подходит в качестве примера, позже добавлю лекций.

**Comment by therods** [comment]
Я закоммитил. У меня два вопроса: нужно ли отлавливать исключения в интерфейсе или того что есть достаточно; если случайно два раза обратиться к файлу .db, то выдается исключение file is locked и лечится оно только перезапуском сервера, не знаю что с ним делать.

**Comment by sadbuttrue1** [comment]
Отлавливать исключения нужно всегда.
Как получается, что ты дважды обращаешься к файлу? Открытие же должно происходить только при создании DAO, а он должен быть один на весь сервер сейчас.

**Comment by sadbuttrue1** [comment]
У тебя на каждой странице свой DAO, почитай про ejb или любой другой способ dependency injection.

**Comment by therods** [comment]
Мне нужно использовать класс taskDao, как java bean или нужно создать отдельный класс, где будет создаваться объект taskDao и его использовать уже?

**Comment by sadbuttrue1** [comment]
TaskDao, но не как java bean, а как ejb.

**Comment by sadbuttrue1** [comment]
Можно так, но ejb прикольней

**Comment by therods** [comment]
Я очень плохо понимаю что нужно сделать. Можешь подсказать, как эта проблема должна решаться, чтобы были какие то зацепки хотя бы что искать. А то я все это время в гугле сижу, а толку ноль.
