### ISSUE TITLE
Create maven project

### ISSUE THREAD

**Issue by sadbuttrue1** [therods/YetAnotherToDoList#3]
Сделайте из пустого репозитория maven-проект с каким-нибудь примитивным pom.xml

**Comment by therods** [comment]
В отдельной ветке закоммитил, не уверен что это то что нужно. Что там вообще должно быть?

**Comment by sadbuttrue1** [comment]
Как минимум, в той ветке есть .iml файл, его не надо добавлять (равно как и директорию .idea).
Удали и добавь .gitignore правильно настроенный (а не в каждой директории свой, он должен быть в корне проекта), чтоб такое не случалось больше.

Сам проект ок, попробуй ещё какую-нибудь зависимость, типа joda-time, подключить.

**Comment by therods** [comment]
Гитигноры добавлял чтобы директории создались, другого способа не нашёл, все остальное поправлю.

**Comment by therods** [comment]
Добавил зависимость, настроил .gitignore в корне. Если удалить гитигноры в директориях то и директории удаляются, так как они пустые. Потом если пулить в локальный репозиторий эти директории исчезают. Наверное лучше оставить их пока там нет других файлов?

**Comment by sadbuttrue1** [comment]
В пустых директориях нет смысла, добавишь, когда будешь добавлять в них файлы.

**Comment by therods** [comment]
Удалил. Это все здесь?

**Comment by sadbuttrue1** [comment]
Да.
