### ISSUE TITLE
Create model layer

### ISSUE THREAD

**Issue by sadbuttrue1** [therods/YetAnotherToDoList#4]
Пока у нас будет только одна сущность — задача.
Поля задачи:
- Название
- Описание
- Время, в которое надо напомнить о неё пользователю
- Контакты (предположим, что имеется в виду просто текстовое поле с телефоном/почтой)

**Comment by therods** [comment]
А из чего он должен состоять, кроме класса задачи?

**Comment by sadbuttrue1** [comment]
Если есть идеи – можешь предложить)
Но вроде больше не надо ничего.

**Comment by therods** [comment]
Я закоммитил, отпиши что там не так.

**Comment by sadbuttrue1** [comment]
Не так:
1. Нет пакета
2. А где у класса поля?

**Comment by therods** [comment]
Он пустым почему то закоммитился, сейчас повторю. А пакет какой должен быть?

**Comment by sadbuttrue1** [comment]
Смотри, у вас в pom.xml группа обозначена как someGroup, это не ок – надо выбрать её.
Она будет корнем пакета. 
Артефакт у вас – YetAnotherToDoList. Это следующий уровень.
Ну и класс относится к модели, значит в итоге получится someGroup.YetAnotherToDoList.model

**Comment by therods** [comment]
а что конкретно не так с someGroup?

**Comment by sadbuttrue1** [comment]
В общем-то всё так, но обычно группа – адрес разработчика наоборот. Например у netcracker.com группа com.netcracker.
Можно так оставить, тогда используй её как корневой пакет.

**Comment by therods** [comment]
Тогда можно закрывать, наверное.
