### ISSUE TITLE
Create collection-based DAO

### ISSUE THREAD

**Issue by sadbuttrue1** [therods/YetAnotherToDoList#5]
Надо сделать слой доступа к данным с полноценным api, но пока без базы данных.
Чтоб сильно не страдать с сериализацией, можно взять http://www.mapdb.org/ или http://www.h2database.com/html/mvstore.html, или что-то ещё похожее.

Исправить в DAO и TaskDAO:
- [x] Из DAO<Id> сделать DAO<K, V> с соответствующей заменой возвращаемых значений
- [x] Метод create должен возвращать V, а не boolean
- [x] В TaskDAO closeStore превратить в https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#finalize()
- [x] Добавить метод получения всех ключей и/или сделать get all отдающим мапу, а не список значений
- [x] Переделать `HashMap<K, V> getMap()` в `Map<K, V> getAll()`

**Comment by sadbuttrue1** [comment]
Поддержать надо стандартный набор операций:
- Добавление
- Удаление
- Обновление
- Поиск

**Comment by therods** [comment]
Как я понял здесь имеется с виду интерфейс (или абстрактный класс?), который описывает методы получения данных из бд, без реализации(или с?) так как бд собственно еще нет. Я все правильно понял? Кстати, вопросы по конкретным темам лучше в здесь задавать или в телеграме?

**Comment by sadbuttrue1** [comment]
Сначала надо модель сделать, а так да, классический dao. 
По конкретным задачам лучше тут.

**Comment by therods** [comment]
А dao получается отдельным слоем от контроллера идет? То есть в отдельном пакете будет?

**Comment by therods** [comment]
Это близко к правде?

**Comment by sadbuttrue1** [comment]
В общем да, но зачем Dao<Id>? Тогда уж Dao<T> и уже конкретную реализацию делать для конкретного класса (например TaskDao<Task>).

**Comment by therods** [comment]
Не очень понял. Как делать реализацию если базы данных нет еще? Если не сложно, попробуй по подробнее мне объяснить в общем все это, я оч поверхностно понимаю что к чему.

**Comment by sadbuttrue1** [comment]
Ты можешь вместо базы данных использовать mapdb или mvstore, посмотри ссылки сверху

**Comment by therods** [comment]
Проблема в том, что я не понимаю что это вообще. Это типо как облачная бд?

**Comment by sadbuttrue1** [comment]
Нет, это библиотеки, которые позволяют использовать специальные коллекции как персистентное хранилище. Т.е. можно писать в коллекцию и она будет сохраняться на диск в фоне и после рестарта у тебя будут те же данные.

**Comment by therods** [comment]
Никак не пойму, как работать с этими библиотеками. Я в общем то понимаю там, как инициализировать бд, но как записывать туда данные не в виде ключ:значение никак не пойму. Мне же по идее нужно чтобы было много полей.

**Comment by sadbuttrue1** [comment]
А в чем проблема сделать MVMap<Integer, Task> например? Это для mvstore.
Ключ пусть просто число с автоинкрементом будет

**Comment by therods** [comment]
Посмотри TaskDao. Примерно так должно быть? Кстати, не совсем понял за что отвечает update, поэтому не реализовал еще.

**Comment by sadbuttrue1** [comment]
Исправить в DAO и TaskDAO:
- [ ] Из DAO<Id> сделать DAO<K, V> с соответствующей заменой возвращаемых значений
- [ ] Метод create должен возвращать V, а не boolean
- [ ] В TaskDAO closeStore превратить в https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#finalize()

**Comment by therods** [comment]
delete тоже возвращать объект? и, кстати, объект возвращается только если не получилось создать, так? А если получилось нулл возвращать или тоже объект?

**Comment by sadbuttrue1** [comment]
delete можно сделать void в общем-то. 
Почему когда не получилось? Всегда.

**Comment by therods** [comment]
В последнем коммите все правильно?

**Comment by sadbuttrue1** [comment]
Похоже на то

**Comment by sadbuttrue1** [comment]
Может стоит добавить метод получения всех ключей? Или сделать get all отдающим мапу, а не список значений.
Пример:
Ты хочешь отрисовать список с кнопками удаления 
Получаешь все объекты, а корректно сделать кнопку удаления для каждого не можешь, так как удвоения происходит по id, а его у тебя нет

**Comment by therods** [comment]
Я чет задумался, что лучше будет. Вроде как со списками работать проще, но если они разделены то это как то не очень.

**Comment by sadbuttrue1** [comment]
С отдельным списком ключей можно работать в формате получил список ключей, итерируешься по нему и для каждого ключа делаешь get конкретного объекта.
С мапой можно просто ходить по мапе, запоминать ключ и делать что нужно с объектом.

**Comment by therods** [comment]
тогда может есть смысл просто получать список ключей вместо объектов?

**Comment by sadbuttrue1** [comment]
Ну вообще, получить сразу пачку – быстрее. Особенно, если будет очень много объектов и база данных.
Лучше всё поддержать, короче.

**Comment by therods** [comment]
я просто не очень понимаю, придется импортировать библиотеки в контроллер сторонние или в стандартных можно с мап работать?

**Comment by sadbuttrue1** [comment]
В методе, который будет возвращать мапу, просто возвращаешь новую мапу (HashMap, например) передав в её конструктор объект MVMap.

**Comment by therods** [comment]
Сделал.

**Comment by sadbuttrue1** [comment]
А почему в методе объявляешь, что возвращаешь HashMap? Сделай более общий Map

**Comment by therods** [comment]
Здесь вроде все.

**Comment by sadbuttrue1** [comment]
А реализацию переделать?
https://github.com/therods/YetAnotherToDoList/blob/master/main/java/someGroup/YetAnotherToDoList/dao/TaskDao.java#L69

**Comment by therods** [comment]
Исправил
