### ISSUE TITLE
Create controller

### ISSUE THREAD

**Issue by sadbuttrue1** [therods/YetAnotherToDoList#6]
Сделать контроллер, с которым потом будет общаться пользовательский интерфейс. Контроллер же будет общаться с DAO.

**Comment by sadbuttrue1** [comment]
Контроллер должен быть своеобразным proxy.
Можно его сделать generic в духе Controller<T extends DAO> или вместо DAO сделать интерфейс DataSource с методами create, read и т.д.
Отнаследовать DAO от этого интерфейса и тогда будет Controller<T extends DataSource>.
Но первый вариант с Controller<T extends DAO> тоже ок.

**Comment by therods** [comment]
А в чем смысл конструкции <T extends DAO> я не могу понять?

**Comment by sadbuttrue1** [comment]
Параметризовать наследником dao

**Comment by therods** [comment]
Никак не могу разобраться, что с ним делать. Насколько я понял контроллер должен дублировать методы дао, при этом вызывая из его методы, так?

**Comment by sadbuttrue1** [comment]
Да

**Comment by therods** [comment]
А как получить key и value в контроллере?
